services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql-magalu'
    environment:
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret123'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_DATABASE=magalu-db'
    ports:
      - '3306:3306'